# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l1tf_R <- function(y, lambda, debug) {
    .Call(`_RcppL1TF_l1tf_R`, y, lambda, debug)
}

l1tf_lambdamax_R <- function(y, debug) {
    .Call(`_RcppL1TF_l1tf_lambdamax_R`, y, debug)
}

