# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l1tf <- function(yvec, lambda, debug = FALSE) {
    .Call(`_RcppL1TF_l1tf`, yvec, lambda, debug)
}

l1tf_lambdamax <- function(yvec, debug = FALSE) {
    .Call(`_RcppL1TF_l1tf_lambdamax`, yvec, debug)
}

superlu_lambdamax <- function(y) {
    .Call(`_RcppL1TF_superlu_lambdamax`, y)
}

superlu_l1tf <- function(y_vec, lambda) {
    .Call(`_RcppL1TF_superlu_l1tf`, y_vec, lambda)
}

